dist: trusty
sudo: false
language: node_js
node_js: '8.10'
cache: yarn
install:
- yarn
jobs:
  include:
    - stage:  test
      script: yarn test
    - stage:  coverage
      script: yarn test:coverage
    - stage: publish
      deploy:
        provider: script
        script: "cp .npmrc.template $HOME/.npmrc && npm publish"
        skip_cleanup: true
        on:
          tags: true